### ISSUE TITLE
Removing typescript dependency

### ISSUE THREAD

**Issue by bitttttten** [ralfting/boilerplate-css-blocks#1]
Is it possible to get this working after removing the typescript support? I find that the build fails to compile (I think it's the rewriter). To me it's wizardry to how it is only working with typescript.

> ReferenceError: styles is not defined

![chrome_2018-05-13_10-50-32](https://user-images.githubusercontent.com/19930241/39965540-77ec9ea8-569b-11e8-9d04-52d08cc8ca76.jpg)

Also strangely this is the same error I encounter when following the css blocks documentaiton :^)

**Comment by ralfting** [comment]
Hey @bitttttten you can use ES6 normally with transpile typescript, I'll update this project to support es6 soon. For now, use extension .ts and write es6, when us has support to es6 you can just update your project (Update Webpack and extensions) keeping your structure.

Feel free to initialize this conversion, thanks @bitttttten.
